##默认使用配置
spring:
  profiles:
    active: dev

##公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mybatis:
#  typeAliasesPackage: com.example.demo.entity
#  mapperLocations: classpath:/xml/*.xml


mybatis-plus:
#  mapper-locations: classpath:com.example.demo.mapper.xml.*.xml
  mapper-locations: classpath:/xml/*.xml
  type-aliases-package: com.example.demo.entity

---

##开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/mis
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource